# Generated by Django 4.0.2 on 2022-02-04 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 41, 48, 614022, tzinfo=utc))),
                ('date_goal', models.DateTimeField(blank=True)),
            ],
        ),
    ]
