# Generated by Django 4.0.2 on 2022-02-04 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 44, 46, 994459, tzinfo=utc)),
        ),
    ]
