# Generated by Django 4.0.2 on 2022-02-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_date_created_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_goal',
            field=models.DateTimeField(null=True),
        ),
    ]
