# Generated by Django 4.0.2 on 2022-02-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_date_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_goal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
